import { CostLine } from "./types";

export const costTemplates: CostLine[] = [
  {
    id: "tmpl-room",
    label: "Room rate / night",
    type: "ROOM",
    applyRule: "PER_NIGHT",
    amount: 100,
    quantity: 1,
    appliesTo: "ALL",
    optional: false,
  },
  {
    id: "tmpl-visa",
    label: "eVisa per pax",
    type: "VISA",
    applyRule: "PER_PAX",
    amount: 50,
    quantity: 1,
    appliesTo: ["SINGLE", "DOUBLE", "TRIPLE"],
    optional: false,
  },
  {
    id: "tmpl-transfer",
    label: "Transfers per pax",
    type: "TRANSFER",
    applyRule: "PER_PAX",
    amount: 20,
    quantity: 1,
    appliesTo: "ALL",
    optional: false,
  },
  {
    id: "tmpl-excursion",
    label: "Excursion per pax",
    type: "EXCURSION",
    applyRule: "PER_PAX",
    amount: 40,
    quantity: 1,
    appliesTo: "ALL",
    optional: true,
  },
  {
    id: "tmpl-ticket",
    label: "Tickets",
    type: "TICKET",
    applyRule: "PER_STAY",
    amount: 500,
    quantity: 1,
    appliesTo: "ALL",
    optional: false,
  },
  {
    id: "tmpl-service",
    label: "Service fee per pax",
    type: "SERVICE_FEE",
    applyRule: "PER_PAX",
    amount: 10,
    quantity: 1,
    appliesTo: "ALL",
    optional: false,
  },
];
